--电信10月份抽红包
CREATE TABLE x191022_user (
  id int UNSIGNED AUTO_INCREMENT,
  openid VARCHAR(36) NOT NULL DEFAULT '',
  nickname varchar(64) not null default '' comment '昵称',
  avatar varchar(255) not null default '' comment '头像',
  phone varchar(15) not null default '' comment '电话',
  share_code varchar(16) not null default '' comment '分享码',
  subscribe tinyint not null default 0 comment '是否关注:1,关注,2,未关注',
  share_num tinyint not null default 0 comment '分享次数',
  game_num tinyint not null default 0 comment '游戏次数',
  game_score int not null default 0 comment '游戏成绩',
  virtual_address_str varchar(128) not null default '' comment '区域',
  virtual_address_code varchar(16) not null default '' comment '区域编号',
  address_str varchar(128) not null default '' comment '地址',
  address_code varchar(128) not null default '' comment '地址编号',
  location varchar(128) not null default '' comment '经纬度',
  status tinyint not null default 0 comment '是否抽奖:1,已抽奖,2,未抽奖',
  money tinyint not null default 0 comment '中奖金额',
  redpack_return_msg varchar(128) not null default '' comment '红包返回信息',
  redpack_describle text comment '红包详情',
  prize_at TIMESTAMP NULL DEFAULT NULL comment '中奖时间',
  last_share_at TIMESTAMP NULL DEFAULT NULL comment '中奖时间',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)ENGINE = innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '用户表';

CREATE TABLE dx190925_help (
  id INT UNSIGNED AUTO_INCREMENT,
  target_user_id int not null default 0 comment '目标id',
  help_user_id int not null default 0 comment '用户id',
  nickname varchar(64) not null default '' comment '昵称',
  avatar varchar(255) not null default '' comment '头像',
  created_at TIMESTAMP NULL DEFAULT NULL,
  updated_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)ENGINE = innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT '分享表';

--电信11月份抽红包
CREATE TABLE `x191119_user` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `openid` varchar(36) NOT NULL DEFAULT '',
  `nickname` varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',
  `avatar` varchar(255) NOT NULL DEFAULT '' COMMENT '头像',
  `subscribe` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否关注1：关注；2：未关注',
  `share_code` varchar(16) NOT NULL DEFAULT '' COMMENT '分享码',
  `share_num` mediumint(9) NOT NULL DEFAULT '0' COMMENT '分享次数',
  `from_code` varchar(16) NOT NULL DEFAULT '' COMMENT '分享方式',
  `topic_num` tinyint(4) NOT NULL DEFAULT '0' COMMENT '答对题数量',
  `virtual_address_str` varchar(128) NOT NULL DEFAULT '' COMMENT '地址',
  `virtual_address_code` varchar(16) NOT NULL DEFAULT '' COMMENT '地址码',
  `address_str` varchar(128) NOT NULL DEFAULT '' COMMENT '解析地址',
  `address_code` varchar(16) NOT NULL DEFAULT '-2' COMMENT '解析地址码',
  `location` varchar(128) NOT NULL DEFAULT '' COMMENT '定位经纬度',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0：未抽奖；1：已抽奖',
  `money` tinyint(4) NOT NULL DEFAULT '0' COMMENT '中奖金额',
  `redpack_return_msg` varchar(128) NOT NULL DEFAULT '' COMMENT '红包返回信息',
  `redpack_describle` text COMMENT '红包详情',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `prize_at` timestamp NULL DEFAULT NULL,
  `last_share_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `openid` (`openid`),
  KEY `status` (`status`),
  KEY `money` (`money`),
  KEY `share_code` (`share_code`),
  KEY `virtual_address_code` (`virtual_address_code`),
  KEY `address_code` (`address_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='电信2019年11月用户表';

--电信11月份抽红包
CREATE TABLE x191212_user (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  openid varchar(36) NOT NULL DEFAULT '',
  nickname varchar(64) NOT NULL DEFAULT '' COMMENT '昵称',
  avatar varchar(255) NOT NULL DEFAULT '' COMMENT '头像',
  name varchar(16) not null default '' comment '姓名',
  phone varchar(16) not null default '' comment '电话',
  address varchar(128) not null default '' comment '邮寄地址',
  topic_num tinyint(4) NOT NULL DEFAULT '0' COMMENT '答对题数量',
  virtual_address_str varchar(128) NOT NULL DEFAULT '' COMMENT '地址',
  virtual_address_code varchar(16) NOT NULL DEFAULT '' COMMENT '地址码',
  address_str varchar(128) NOT NULL DEFAULT '' COMMENT '解析地址',
  address_code varchar(16) NOT NULL DEFAULT '-2' COMMENT '解析地址码',
  location varchar(128) NOT NULL DEFAULT '' COMMENT '定位经纬度',
  status tinyint(4) NOT NULL DEFAULT 0 COMMENT '0：未抽奖；1：已抽奖',
  prize_id tinyint(4) NOT NULL DEFAULT 0 COMMENT '奖品ID',
  prize varchar(128) not null default '' comment '奖品',
  created_at timestamp NULL DEFAULT NULL,
  updated_at timestamp NULL DEFAULT NULL,
  prize_at timestamp NULL DEFAULT NULL,
  PRIMARY KEY (id),
  KEY openid (openid),
  KEY status (status),
  KEY virtual_address_code (virtual_address_code),
  KEY address_code (address_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='电信2019年12月用户表';
